name: Build and Push Docker Image

# Trigger on any push or pull request to any branch
on:
  push:
    branches:
      - '**'   # Trigger on all branches
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx to enable multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub (or any other Docker registry) using secrets
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   # DockerHub username stored in secrets
        password: ${{ secrets.DOCKER_PASSWORD }}   # DockerHub password stored in secrets

    # Build the Docker image and tag it with the branch name
    - name: Build and Tag Docker Image
      run: |
        docker build -t steijntjuh/livedj-auth-service:${GITHUB_REF##*/} .

    # Push the Docker image to DockerHub using the branch name as the tag
    - name: Push Docker Image
      run: |
        docker push steijntjuh/livedj-auth-service:${GITHUB_REF##*/}
